### ISSUE TITLE
Why not add UI for chatting? like react.js or next.js, angular, etc.

### ISSUE THREAD

**Issue by hechanghong** [vontanne/nestjs-socketio-chat#2]
**Feature Description**
Briefly describe the feature you're suggesting.

**Problem and Motivation**
What problem does this feature solve? Why do you think this feature should be added?

**Proposed Solution**
Describe your solution. How will it solve the problem?

**Alternatives Considered**
Did you consider any alternative solutions or features?

**Additional Context**
Provide any additional context or screenshots about the feature request here.

**Potential Impact**
Consider and describe any potential impacts of this feature.

**Urgency**
How urgent is this feature? Low/Medium/High

**Willingness to Contribute**
Are you willing to contribute to the development of this feature?

---

Thanks for contributing to the enhancement of the project!

**Comment by vontanne** [comment]
Thank you for your suggestion! This repository focuses on the backend implementation using NestJS and Socket.io. However, anyone interested is welcome to create a frontend for it using React, Next.js, Angular, or any other framework of their choice. Contributions are always appreciated!
