### ISSUE TITLE
all i can see is `Hello World`

### ISSUE THREAD

**Issue by minbokang** [vontanne/nestjs-socketio-chat#3]
when `npm run start:dev`

all i can see is `Hello World`

chk plz.

**Comment by vontanne** [comment]
Hi @minbokang 

Thank you for bringing this up! The current state of this repository is the backend of the chat application. The "Hello World" message you are seeing is part of the backend setup.

To test the functionality properly, you should use tools like Postman to send and receive events via Socket.IO. For more detailed information and instructions on how to use the backend, please refer to the Wiki section of this repository, where you will find documentation that should help guide you through the process.
